package gui;
import common.data.Student;
import common.data.StudentDatabase;
import gui.common.tablemodels.StudentTableModel;
import java.io.IOException;
import javax.swing.JOptionPane;

public class AddStudents extends javax.swing.JPanel {
    StudentTableModel tableModel;
    public String FullName = "", Department = "", gender = "Male";
    int StudentID = 0, age = 0;
    double GPA = 0;
    public boolean validText(String input){
        return (input.length() > 0);
    }
    public boolean validID(String input){
        if(input.length() == 0)
            return false;
        try {
            int value = Integer.parseInt(input);
            return (value >= 0);
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public boolean validGPA(String input){
        if(input.length() == 0)
            return false;
        try {
            double value = Double.parseDouble(input);
            return !(value < 0 || value > 4);
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public boolean validAge(String input){ //age between 0 and 99
       if(input.length() == 0)
            return false;
        try {
            int value = Integer.parseInt(input);
            return (value >= 0 && value <= 99);
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public AddStudents(StudentTableModel studentTable) {
        initComponents();
        tableModel = studentTable;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        StudentIDText = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();
        FullNameText = new javax.swing.JLabel();
        FullNameTextField = new javax.swing.JTextField();
        AgeText = new javax.swing.JLabel();
        AgeTextField = new javax.swing.JTextField();
        DepartmentText = new javax.swing.JLabel();
        DepartmentTextField = new javax.swing.JTextField();
        GPAText = new javax.swing.JLabel();
        GPATextField = new javax.swing.JTextField();
        GenderText = new javax.swing.JLabel();
        GenderComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(130, 195, 130));
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Add Student");

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        StudentIDText.setText("StudentID");

        StudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextFieldActionPerformed(evt);
            }
        });

        FullNameText.setText("Full Name");

        FullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameTextFieldActionPerformed(evt);
            }
        });

        AgeText.setText("Age");

        AgeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextFieldActionPerformed(evt);
            }
        });

        DepartmentText.setText("Department");

        DepartmentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentTextFieldActionPerformed(evt);
            }
        });

        GPAText.setText("GPA");

        GPATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPATextFieldActionPerformed(evt);
            }
        });

        GenderText.setText("Gender");

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GPAText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jButton2)
                            .addGap(177, 177, 177)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(StudentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DepartmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(GenderText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDText)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullNameText)
                    .addComponent(FullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeText)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderText)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartmentText)
                    .addComponent(DepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPAText)
                    .addComponent(GPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validText(StudentIDTextField.getText())) {
            StudentIDTextField.requestFocus();
        } else if(!validText(FullNameTextField.getText())){
           FullNameTextField.requestFocus();
        } else if (!validAge(AgeTextField.getText())) {
            AgeTextField.requestFocus();
        } else if (!validText(DepartmentTextField.getText())) {
            DepartmentTextField.requestFocus();
        } else if (!validGPA(GPATextField.getText())) {
            GPATextField.requestFocus();
        } else{
            try {
                Student newstudent = new Student(StudentID, FullName, age, gender, Department, GPA);
                StudentDatabase p = StudentDatabase.getInstance("Students.txt");
                if(p.contains(newstudent.getSearchKey())){
                    JOptionPane.showMessageDialog(this, "Student with this ID already exists", "Validation Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    p.insertRecord(newstudent);
                    p.saveToFile();
                    tableModel.refreshTable();
                    JOptionPane.showMessageDialog(this, "Student Added Successfully", "Addition Confirmed", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException ex) {
                System.out.println("IOException");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.showPanel("home");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void StudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextFieldActionPerformed
        // TODO add your handling code here:
        String currentID = StudentIDTextField.getText();
        if(validID(currentID) == false){
            JOptionPane.showMessageDialog(this, "Invalid ID", "Validation Error", JOptionPane.ERROR_MESSAGE);
            StudentIDTextField.setText(StudentID + "");
        }else{
            StudentID = Integer.parseInt(currentID);
            FullNameTextField.requestFocus();
        }
    }//GEN-LAST:event_StudentIDTextFieldActionPerformed

    private void FullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameTextFieldActionPerformed
        // TODO add your handling code here:
        String currentFullname = FullNameTextField.getText();
        if(validText(currentFullname) == false){
            JOptionPane.showMessageDialog(this, "Invalid Name", "Validation Error", JOptionPane.ERROR_MESSAGE);
            FullNameTextField.setText(FullName);
        }else{
            FullName = currentFullname;
            AgeTextField.requestFocus();
        }
    }//GEN-LAST:event_FullNameTextFieldActionPerformed

    private void AgeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextFieldActionPerformed
        // TODO add your handling code here:
        String currentAge = AgeTextField.getText();
        if(validAge(currentAge) == false){
            JOptionPane.showMessageDialog(this, "Invalid Age", "Validation Error", JOptionPane.ERROR_MESSAGE);
            AgeTextField.setText(age + "");
        }else{
            age = Integer.parseInt(currentAge);
            GenderComboBox.requestFocus();
        }
    }//GEN-LAST:event_AgeTextFieldActionPerformed

    private void DepartmentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentTextFieldActionPerformed
        // TODO add your handling code here:
        String currentdep = DepartmentTextField.getText();
        if(validText(currentdep) == false){
            JOptionPane.showMessageDialog(this, "Invalid Department", "Validation Error", JOptionPane.ERROR_MESSAGE);
            DepartmentTextField.setText(Department);
        }else{
            Department = currentdep;
            GPATextField.requestFocus();
        }
    }//GEN-LAST:event_DepartmentTextFieldActionPerformed

    private void GPATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPATextFieldActionPerformed
        // TODO add your handling code here:
        String currentGPA = GPATextField.getText();
        if(validGPA(currentGPA) == false){
            JOptionPane.showMessageDialog(this, "Invalid GPA", "Validation Error", JOptionPane.ERROR_MESSAGE);
            GPATextField.setText(GPA + "");
        }else{
            GPA = Double.parseDouble(currentGPA);
        }
    }//GEN-LAST:event_GPATextFieldActionPerformed

    private void GenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboBoxActionPerformed
        // TODO add your handling code here:
        gender = GenderComboBox.getSelectedItem().equals("Male") ? "Male" : "Female";
        DepartmentTextField.requestFocus();
    }//GEN-LAST:event_GenderComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeText;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JLabel DepartmentText;
    private javax.swing.JTextField DepartmentTextField;
    private javax.swing.JLabel FullNameText;
    private javax.swing.JTextField FullNameTextField;
    private javax.swing.JLabel GPAText;
    private javax.swing.JTextField GPATextField;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderText;
    private javax.swing.JLabel StudentIDText;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}