/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.io.IOException;

import common.data.Student;
import common.data.StudentDatabase;
import gui.common.fieldcheckers.NonEmptyFieldChecker;
import gui.common.tablemodels.StudentTableModel;

/**
 *
 * @author Youssef
 */
public class EditStudent extends javax.swing.JPanel {

    private static EditStudent instance;
    @SuppressWarnings("unused")
    private final NonEmptyFieldChecker nameChecker;
    @SuppressWarnings("unused")
    private final NonEmptyFieldChecker departmentChecker;
    private Student s;
    private StudentTableModel tableModel;
    StudentDatabase db;

    /**
     * Creates new form EditStudent
     */
    public EditStudent(StudentTableModel tableModel, StudentDatabase db) {
        this.db = db;
        this.tableModel = tableModel;
        initComponents();
        instance = this;
        nameChecker = new NonEmptyFieldChecker(studentNameLabel, studentNameLabel.getText(), "can't be empty",
                studentNameInput);
        departmentChecker = new NonEmptyFieldChecker(departmentLabel, departmentLabel.getText(), "can't be empty",
                departmentInput);
    }

    public static void edit(String studentId) {
        MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(instance);
        frame.showPanel("editstudent");
        instance.s = instance.db.getRecord(studentId);
        instance.genderInput.setSelectedIndex(instance.s.getGender().equals("Male") ? 0 : 1);
        instance.ageInput.setValue(instance.s.getAge());
        instance.studentNameInput.setText(instance.s.getName());
        instance.idInput.setText(studentId);
        instance.departmentInput.setText(instance.s.getDepartment());
        instance.gpaInput.setValue(instance.s.getGpa());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        studentNameLabel = new javax.swing.JLabel();
        studentNameInput = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        gpaLabel = new javax.swing.JLabel();
        genderInput = new javax.swing.JComboBox<>();
        departmentInput = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        goBackButton = new javax.swing.JButton();
        ageInput = new javax.swing.JSpinner();
        gpaInput = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setText("Edit Student");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        add(title, gridBagConstraints);

        idLabel.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(idLabel, gridBagConstraints);

        idInput.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(idInput, gridBagConstraints);

        studentNameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(studentNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(studentNameInput, gridBagConstraints);

        ageLabel.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(ageLabel, gridBagConstraints);

        genderLabel.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(genderLabel, gridBagConstraints);

        departmentLabel.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(departmentLabel, gridBagConstraints);

        gpaLabel.setText("GPA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(gpaLabel, gridBagConstraints);

        genderInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(genderInput, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(departmentInput, gridBagConstraints);

        saveButton.setText("Save");
        saveButton.addActionListener(this::saveActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        add(saveButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        add(jSeparator1, gridBagConstraints);

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(this::goBackButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        add(goBackButton, gridBagConstraints);

        ageInput.setModel(new javax.swing.SpinnerNumberModel(16, 16, 34, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(ageInput, gridBagConstraints);

        gpaInput.setModel(new javax.swing.SpinnerNumberModel(2.0d, 0.0d, 4.0d, 0.1d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(gpaInput, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveActionPerformed
        this.s.setAge((int) this.ageInput.getValue());
        this.s.setName(this.studentNameInput.getText());
        this.s.setDepartment(this.departmentInput.getText());
        this.s.setGender(this.genderInput.getItemAt(this.genderInput.getSelectedIndex()));
        this.s.setGpa((double) this.gpaInput.getValue());
        this.tableModel.refreshTable();
        try {
            this.db.saveToFile();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }// GEN-LAST:event_saveActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_goBackButtonActionPerformed
        MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.showPanel("searchupdatestudents");
    }// GEN-LAST:event_goBackButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageInput;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField departmentInput;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JComboBox<String> genderInput;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JSpinner gpaInput;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField studentNameInput;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}