package GUI;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import GUI.MainWindow;
public class Login extends javax.swing.JPanel {

    public String username = "", password = "";
    public boolean validText(String input){
        return (input.length() > 0);
    }
    public boolean validGPA(String input){
        if(input.length() == 0)
            return false;
        try {
            double value = Double.parseDouble(input);
            if(value < 0 || value > 4)
                return false;
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public boolean validAge(String input){ //age between 0 and 99
       if(input.length() == 0)
            return false;
        try {
            int value = Integer.parseInt(input);
            return (value >= 0 && value <= 99);
        } catch (NumberFormatException e) {
            return false;
        }
    }
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PasswordText = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(153, 200, 225));

        Title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title.setText("Student Management System");

        UsernameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(153, 255, 153));
        UsernameLabel.setText("Username:");

        PasswordLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(153, 255, 153));
        PasswordLabel.setText("Password:");

        UsernameText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PasswordText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameText)
                    .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Title)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
        if(validText(UsernameText.getText()) == false){
            JOptionPane.showMessageDialog(this, "Invalid Text", "Validation Error", JOptionPane.ERROR_MESSAGE);
            UsernameText.setText(username);
        }else{
            username = UsernameText.getText();
        }

    }//GEN-LAST:event_UsernameTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean valid = false;
        if(username.equals("taha") && password.equals("9999"))
        valid = true;
        if(valid){
            JOptionPane.showMessageDialog(this, "Login Successful", "Login Confirmation", JOptionPane.INFORMATION_MESSAGE);
            MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
            frame.showPanel("home");
        }else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
        String currentPass = String.valueOf(PasswordText.getPassword());
        if(validText(currentPass) == false){
            JOptionPane.showMessageDialog(this, "Invalid Text", "Validation Error", JOptionPane.ERROR_MESSAGE);
            PasswordText.setText(password);
        }else{
            password = currentPass;
        }
    }//GEN-LAST:event_PasswordTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables


}
