package gui;
import common.data.AdminDatabase;
import gui.common.fieldcheckers.BasicValidators;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JPanel {
    AdminDatabase database;
    public Login(AdminDatabase database) {
        initComponents();
        this.database = database;
    }

    private void submit() {
        if (!BasicValidators.validate(usernameInput, BasicValidators.username)) {
            usernameInput.requestFocus();
        } else if (!BasicValidators.validate(passwordInput, BasicValidators.password)) {
            passwordInput.requestFocus();
        } else{
            if(database.contains(usernameInput.getText() + "," + String.valueOf(passwordInput.getPassword()))){
                usernameInput.setText("");
                passwordInput.setText("");
                JOptionPane.showMessageDialog(this, "Login Successful", "Login Confirmation",
                        JOptionPane.INFORMATION_MESSAGE);
                MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
                frame.showPanel("home");
            }else{
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(130, 195, 130));
        setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setText("Student Management System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 1);
        add(title, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        usernameLabel.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        add(usernameLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        add(passwordLabel, gridBagConstraints);

        usernameInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        add(usernameInput, gridBagConstraints);

        submitButton.setBackground(new java.awt.Color(0, 204, 255));
        submitButton.setText("Login");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 1);
        add(submitButton, gridBagConstraints);

        passwordInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        add(passwordInput, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameInputActionPerformed
        if (unc.checkValid())
            usernameInput.transferFocus();
    }// GEN-LAST:event_usernameInputActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitButtonActionPerformed
        submit();
    }// GEN-LAST:event_submitButtonActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordInputActionPerformed
        submit();
    }// GEN-LAST:event_passwordInputActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
