package gui;

import common.data.StudentDatabase;
import gui.common.tablemodels.StudentTableModel;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class SearchAndUpdate extends javax.swing.JPanel {
    StudentTableModel tableModel;
    TableRowSorter<StudentTableModel> tableSorter;
    ListSelectionModel selectionModel;
    StudentDatabase db;

    public SearchAndUpdate(StudentTableModel studentTable) {
        initComponents();
        tableModel = studentTable;
        studentsViewTable.setModel(tableModel);
        // Sorter initialization for use with filter() when search input is updated
        tableSorter = new TableRowSorter<>(tableModel);
        studentsViewTable.setRowSorter(tableSorter);

        // Selection Handling
        selectionModel = studentsViewTable.getSelectionModel(); // Selection Model == Selection Manager
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Allow only one row to be selected
        selectionModel.addListSelectionListener((event) -> {
            editSelectedButton.setEnabled(!selectionModel.isSelectionEmpty()); // Enable edit button if student is
                                                                               // selected
        });
    }

    // On searchInput keyTyped/ actionPerformed
    private void filter(String key) {
        if (key.trim().length() == 0) {
            // Reset filter if key is empty
            tableSorter.setRowFilter(null);
        } else {
            // Set an OR filter that looks for the key in all IDs and Names
            var filters = new ArrayList<RowFilter<Object, Object>>();
            filters.add(RowFilter.regexFilter("(?i)" + key, studentsViewTable.getColumn("Name").getModelIndex()));
            filters.add(RowFilter.regexFilter("(?i)" + key, studentsViewTable.getColumn("ID").getModelIndex()));
            tableSorter.setRowFilter(RowFilter.orFilter(filters));
        }
    }

    // On editButton pressed
    private void selectAndEdit() {
        // Get selected row -> get ID column -> get ID -> pass ID to edit window
        var row = studentsViewTable.getSelectedRow();
        var idColumn = studentsViewTable.getColumn("ID").getModelIndex();
        EditStudent.edit(this.tableModel.getValueAt(row, idColumn).toString(), db);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        studentsViewTable = new javax.swing.JTable();
        searchBar = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        editSelectedButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(130, 195, 130));
        setEnabled(false);
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setText("Update Students");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        add(title, gridBagConstraints);

        backButton.setBackground(new java.awt.Color(255, 153, 153));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 19, 0, 0);
        add(backButton, gridBagConstraints);

        studentsViewTable.setModel(studentsViewTable.getModel());
        tableScrollPane.setViewportView(studentsViewTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(tableScrollPane, gridBagConstraints);

        searchBar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        add(searchBar, gridBagConstraints);

        searchLabel.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(searchLabel, gridBagConstraints);

        editSelectedButton.setBackground(new java.awt.Color(0, 204, 255));
        editSelectedButton.setText("Edit Selected");
        editSelectedButton.setEnabled(false);
        editSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(editSelectedButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonPressed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonPressed
        selectAndEdit();
    }// GEN-LAST:event_editButtonPressed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        MainWindow frame = (MainWindow) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.showPanel("home");
    }//GEN-LAST:event_backButtonMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBarActionPerformed
        filter(searchBar.getText());
    }// GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_searchBarKeyTyped
        filter(searchBar.getText());
    }// GEN-LAST:event_searchBarKeyTyped

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton editSelectedButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTable studentsViewTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}