package gui;

import common.data.StudentDatabase;
import gui.common.tablemodels.StudentTableModel;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class SearchAndUpdate extends javax.swing.JPanel {
    StudentTableModel tableModel;
    TableRowSorter<StudentTableModel> tableSorter;

    public SearchAndUpdate() {
        initComponents();
        try {
            tableModel = new StudentTableModel(StudentDatabase.getInstance("Students.txt"));
            studentsViewTable.setModel(tableModel);
        } catch (IOException ex) {
            System.getLogger(SearchAndUpdate.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            return;
        }
        tableSorter = new TableRowSorter<StudentTableModel>(tableModel);
        studentsViewTable.setRowSorter(tableSorter);
    }

    private void filter(String key) {
        if (key.trim().length() == 0) {
            tableSorter.setRowFilter(null);
        } else {
            var filters = new ArrayList<RowFilter<Object, Object>>();
            filters.add(RowFilter.regexFilter("(?i)" + key, studentsViewTable.getColumn("Name").getModelIndex()));
            filters.add(RowFilter.regexFilter("(?i)" + key, studentsViewTable.getColumn("ID").getModelIndex()));
            tableSorter.setRowFilter(RowFilter.orFilter(filters));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        studentsViewTable = new javax.swing.JTable();
        searchBar = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setEnabled(false);
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title.setText("Update Students");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        add(title, gridBagConstraints);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 19, 0, 0);
        add(backButton, gridBagConstraints);

        studentsViewTable.setModel(studentsViewTable.getModel());
        tableScrollPane.setViewportView(studentsViewTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(tableScrollPane, gridBagConstraints);

        searchBar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(searchBar, gridBagConstraints);

        searchLabel.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(searchLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBarActionPerformed
        filter(searchBar.getText());
    }// GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_searchBarKeyTyped
        filter(searchBar.getText());
    }// GEN-LAST:event_searchBarKeyTyped

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTable studentsViewTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}